import React, { useEffect, useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { getMockPosts } from '../mock/postsMock'

const Svg = ({ children }) => (
  <svg
    width='22'
    height='22'
    viewBox='0 0 24 24'
    fill='none'
    xmlns='http://www.w3.org/2000/svg'
    className='shrink-0'
  >
    {children}
  </svg>
)

const iconFor = (kind) => {
  if (kind === 'chat') {
    return (
      <Svg>
        <path
          d='M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z'
          stroke='currentColor'
          strokeWidth='2'
          strokeLinejoin='round'
        />
      </Svg>
    )
  }
  if (kind === 'comment') {
    return (
      <Svg>
        <path
          d='M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z'
          stroke='currentColor'
          strokeWidth='2'
          strokeLinejoin='round'
        />
        <path
          d='M7 18h6'
          stroke='currentColor'
          strokeWidth='2'
          strokeLinecap='round'
        />
      </Svg>
    )
  }
  if (kind === 'reaction') {
    return (
      <Svg>
        <path
          d='M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 22l7.8-8.6 1-1a5.5 5.5 0 0 0 0-7.8Z'
          stroke='currentColor'
          strokeWidth='2'
          strokeLinejoin='round'
          strokeLinecap='round'
        />
      </Svg>
    )
  }
  if (kind === 'video') {
    return (
      <Svg>
        <path
          d='M14 10.5 20 7v10l-6-3.5V17a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v3.5Z'
          stroke='currentColor'
          strokeWidth='2'
          strokeLinejoin='round'
        />
      </Svg>
    )
  }
  if (kind === 'post') {
    return (
      <Svg>
        <path
          d='M8 3h8a3 3 0 0 1 3 3v12a3 3 0 0 1-3 3H8a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3Z'
          stroke='currentColor'
          strokeWidth='2'
          strokeLinejoin='round'
        />
        <path
          d='M12 8v8M8 12h8'
          stroke='currentColor'
          strokeWidth='2'
          strokeLinecap='round'
        />
      </Svg>
    )
  }
  return null
}

const formatTime = (iso) => {
  try {
    const dt = new Date(iso)
    if (Number.isNaN(dt.getTime())) return ''
    return dt.toLocaleString(undefined, { hour: '2-digit', minute: '2-digit' })
  } catch {
    return ''
  }
}

const ActivityModal = ({ isOpen, activity, onClose }) => {
  const navigate = useNavigate()

  const kind = activity?.activityType || activity?.badgeIcon || ''
  const title = useMemo(() => {
    if (kind === 'chat') return 'New Chat'
    if (kind === 'comment') return 'New Comment'
    if (kind === 'reaction') return 'New Reaction'
    if (kind === 'video') return 'Video Activity'
    if (kind === 'post') return 'New Post'
    return 'Activity'
  }, [kind])

  const hint = useMemo(() => {
    if (kind === 'chat') return 'A message was sent. Jump back into the thread.'
    if (kind === 'comment') return 'A comment was added. Open the post to view the thread.'
    if (kind === 'reaction') return 'A reaction was made. Open the post to see details.'
    if (kind === 'video') return 'A video interaction happened. Open reels to continue.'
    if (kind === 'post') return 'A new post was created. Open it to view.'
    return 'This item was generated by your activity feed.'
  }, [kind])

  useEffect(() => {
    if (!isOpen) return undefined
    const onKey = (e) => {
      if (e.key === 'Escape') onClose?.()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [isOpen, onClose])

  if (!isOpen || !activity) return null

  return (
    <div
      className='fixed inset-0 z-[1100] flex items-center justify-center bg-black/55 p-4'
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose?.()
      }}
    >
      <div className='w-full max-w-sm overflow-hidden rounded-2xl border border-[var(--hx-border)] bg-[var(--hx-surface)] shadow-xl'>
        <div className='flex items-start justify-between gap-3 border-b border-[var(--hx-border)] bg-[var(--hx-surface-glass)] p-4 supports-[backdrop-filter]:backdrop-blur-md'>
          <div className='flex items-start gap-3'>
            <div className='grid h-10 w-10 place-items-center rounded-full border border-[var(--hx-border)] bg-[var(--hx-surface)] text-[var(--hx-text)]'>
              {iconFor(kind)}
            </div>
            <div className='min-w-0'>
              <p className='truncate text-base font-extrabold text-[var(--hx-text)]'>{title}</p>
              <p className='truncate text-xs text-[var(--hx-text-muted)]'>
                {activity.createdAt ? formatTime(activity.createdAt) : ''}
              </p>
            </div>
          </div>
          <button
            type='button'
            onClick={() => onClose?.()}
            className='rounded-full border border-[var(--hx-border)] bg-[var(--hx-surface)] px-3 py-1.5 text-xs font-bold text-[var(--hx-text)] hover:bg-[var(--hx-surface-2)]'
          >
            Close
          </button>
        </div>

        <div className='p-4'>
          <p className='text-sm text-[var(--hx-text-muted)]'>{hint}</p>

          <div className='mt-3 overflow-hidden rounded-2xl border border-[var(--hx-border)] bg-[var(--hx-surface-2)]'>
            {activity.avatarFull || activity.avatar ? (
              <img
                src={activity.avatarFull || activity.avatar}
                alt={title}
                className='h-48 w-full object-cover'
                loading='lazy'
                decoding='async'
              />
            ) : (
              <div className='grid h-48 place-items-center text-sm text-[var(--hx-text-muted)]'>
                No preview available
              </div>
            )}
          </div>

          <div className='mt-3 flex gap-2'>
            {kind === 'chat' ? (
              <button
                type='button'
                onClick={() => {
                  onClose?.()
                  if (activity.friendId) {
                    navigate(`/home/${activity.friendId}`)
                  } else {
                    navigate('/home/messages')
                  }
                }}
                className='flex-1 rounded-full bg-[var(--hx-accent)] px-4 py-2 text-xs font-extrabold text-white'
              >
                Open Chat
              </button>
            ) : null}

            {kind === 'video' ? (
              <button
                type='button'
                onClick={() => {
                  onClose?.()
                  navigate('/home/video')
                }}
                className='flex-1 rounded-full bg-[var(--hx-accent)] px-4 py-2 text-xs font-extrabold text-white'
              >
                Open Reels
              </button>
            ) : null}

            {(kind === 'reaction' || kind === 'comment' || kind === 'post') && activity.postId ? (
              <button
                type='button'
                onClick={() => {
                  onClose?.()
                  const post = getMockPosts().find((p) => p.id === activity.postId) || null
                  navigate(`/home/post/${activity.postId}`, { state: { post } })
                }}
                className='flex-1 rounded-full bg-[var(--hx-accent)] px-4 py-2 text-xs font-extrabold text-white'
              >
                Open Post
              </button>
            ) : null}

            <button
              type='button'
              onClick={() => onClose?.()}
              className='rounded-full border border-[var(--hx-border)] bg-[var(--hx-surface)] px-4 py-2 text-xs font-extrabold text-[var(--hx-text)] hover:bg-[var(--hx-surface-2)]'
            >
              Dismiss
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default ActivityModal
